steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gin-prod/gin-cluster', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gin-prod/gin-cluster']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'minha-aplicacao'
      - '--image=gcr.io/gin-prod/gin-cluster'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
options:
  logging: NONE
